catalog:
  "@types/node": ^26.1.1
  "@typescript/native-preview": ^7.0.0-dev.20260707.2
  taze: ^19.14.1
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@^0.2.4
  vite-plus: ^0.2.4
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"

# Prefer catalog
catalogMode: prefer
shellEmulator: true
ignoreWorkspaceRootCheck: false
